### ISSUE TITLE
Samsung Continuity service not working. 

### ISSUE THREAD

**Issue by vink2212** [Bananz0/GalaxyBookEnabler#5]
Earlier this script allowed us to use the continuity service but for about a month or so, the service has been broken.

Multi control and Samsung account work perfectly but you aren't able to copy and paste or configure the how things work. On microsoft store the app just blanks out and does not allow you to open it.

**Comment by Bananz0** [comment]
I think the continuity service is supposed to behave that way. On my end, the store blanks it too but as long as it's installed, everything should be fine.

Configuring the settings should be on the Samsung Settings app of which I haven't been able to get working since it needs a device present. I haven't figured how to spoof the device nor have I heard of anyone able to do it successfully.

I have tested the continuity service by using another laptop signed in to the same Samsung account with the continuity service installed on both.

**Comment by vink2212** [comment]
Yeah, so the reason I brought this up was because when I first downloaded this script, back when I opened the || token error, I was able to use the continuity service without issue. It opened up for me and I was able to configure settings. I first noticed something changed when multi-control was working but the clipboard feature (where you can copy text or images from one device and paste on another) had stopped working. Coincidentally the way to enable that feature is via the contunity service.

**Comment by Bananz0** [comment]
The continuity service is working as of the newest update albeit intermittently, I suspect this is because we don't have Samsung Settings installed.
